name: Deploy Website Sekolah

on:
  push:
    branches:
      - main  # Ganti jika nama branch utama Anda 'master'

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Rebuild & Restart Container
        run: |
          cd /home/r14/apps/web-sekolah
          git pull origin main
          docker compose down
          docker compose up -d --build